;;; publish.el --- Build the blog with org-static-blog -*- lexical-binding: t; -*-

;; Install org-static-blog from MELPA
(require 'package)
(setq package-user-dir (expand-file-name ".packages" default-directory))
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
(unless (package-installed-p 'org-static-blog)
  (package-refresh-contents)
  (package-install 'org-static-blog))

(require 'org-static-blog)

;; ============================================================
;; CONFIGURE YOUR BLOG HERE
;; ============================================================

(setq org-static-blog-publish-title "deadmeme.dev")
(setq org-static-blog-publish-url "https://deadmeme.dev/")
(setq org-static-blog-publish-directory "./public/")
(setq org-static-blog-posts-directory "./posts/")
(setq org-static-blog-drafts-directory "./drafts/")
(setq org-static-blog-enable-tags t)
(setq org-static-blog-use-preview t)
(setq org-static-blog-preview-convert-titles t)
(setq org-static-blog-preview-ellipsis "...")
(setq org-static-blog-index-length 10)

;; ============================================================
;; HTML HEAD - CSS goes here
;; ============================================================

(setq org-static-blog-page-header
      "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
<link rel=\"stylesheet\" type=\"text/css\" href=\"/style.css\">")

;; ============================================================
;; PAGE PREAMBLE - Header/nav shown on every page
;; ============================================================

(setq org-static-blog-page-preamble
      "<header>
<h1><a href=\"/\">deadmeme.dev</a></h1>
<nav>
<a href=\"/\">Home</a> |
<a href=\"/archive.html\">Archive</a> |
<a href=\"/tags.html\">Tags</a> |
<a href=\"/rss.xml\">RSS</a>
</nav>
<hr>
</header>")

;; ============================================================
;; PAGE POSTAMBLE - Footer shown on every page
;; ============================================================

(setq org-static-blog-page-postamble
      "<footer id=\"postamble\">
<p>Written in org-mode. Generated by org-static-blog.</p>
</footer>")

;; ============================================================
;; INDEX PAGE PREAMBLE - Extra content on homepage only
;; ============================================================

(setq org-static-blog-index-front-matter
      "<p>Welcome. This is where I write what's in my head.</p>
<hr>")

;; ============================================================
;; PUBLISH
;; ============================================================

(org-static-blog-publish)
