#+TITLE: Chapter One - Hope.
#+DATE: <2026-01-01>
#+FILETAGS: :reverend_insanity:

* Background

This is a blog I've been meaning to write for the longest time - never got myself to do it till now. Thought this could be the "start of a year" thing, however transient and arbitrary that might seem. I've always wanted to write about the one book that changed my life - reverend insanity, but I never really figured out how I should approach it.

Should I write about the world building? The characters? The depth of story telling that truly makes this book one of a kind? Then I realized - why not use the baseline provided to me in the book - "The Legends of Ren Zu" for my narrative guidance? And that's what this series is going to be.

It's my personal understanding of the legends, as well as the meagre philosophy that is present in them. The book by itself seems simplistic and almost childish - but I personally believe this book captures the human spirit, and the journey one takes in life.

Our story of Ren Zu starts with him as the "human ancestor". Who was created from the blue sea of life - where all living beings are created. He had 10 children, and together with them - he experiences countless legends. And these stories are narrated to us in this book that is - "The Legends of Ren Zu".

With this background in mind, let us begin our journey into the first chapter.

* Chapter One - Hope.

The world was just formed, and Ren Zu was born - the human ancestor - from the Blue Sea of Life. The world was a savage wilderness, and beasts and wild creatures roamed the land. Ren Zu lived a difficult life, eating raw meat and drinking blood - a life devoid of anything but survival.

Among the wild beasts, there existed a group known as "predicaments" - these wild beasts longed for the taste of fresh human meat, as they had never experienced it before. And Ren Zu didn't have a strong body, nor sharp teeth or claws to defend himself. And all he could do, was run away and hide.

One day - while he was barely surviving - three Gu came upto him, and said - "As long as you give us your lifespan, we will help you through this difficulty". Ren Zu, truly lost and helpless - agreed to these 3 gu.

He first gave his youth to the biggest Gu among the three. This gu, granted him Strength.

With strength, his life began to change - he was able to hunt for food, and fend for himself. Ren Zu felt like he was no longer relegated to the bottom of the food chain. He fought bravely, as he now had strength, that he didn't have before. But soon, he realized - strength had to heal, recover and had to be cultivated, and not to mention - when faced with an entire group of predicaments, his strength just wasn't enough.

Ren Zu, realizing this - gave away his middle age to the most beautiful Gu among the three. This, was Wisdom Gu.

With wisdom, Ren Zu was able to think and reflect. He began to reason about all his experiences and realised, using wisdom always worked better than using raw strength. By relying on both his strength and his wisdom, Ren Zu began to conquer the goals he formerly could not - he was able to kill many predicaments, and was able to grow.

But good things don't last. Ren Zu had traded his youth for strength, and middle age for wisdom - and all he was now was frail old man, who was unable to be the proud warrior, or the wise strategist as he once was. Strength and Wisdom Gu, realising Ren Zu had nothing to give them or cultivate them, scorned him and left.

He was surrounded by predicaments, and without his Wisdom and Strength - he was helpless. He was old and could not run, and his brain was muddled and slow. As he fell to the ground weakly, this time - the third Gu said to him - "Human, take me up. I will help you ward off these predicaments".

Ren Zu tearfully replied, "Gu, I don't have anything left to give. Strength and Wisdom Gu have abandoned me. I only have my old age left! While it is not as prized as my youth and my middle age, giving you my old age would immediately kill me. Even though I am surrounded by predicaments, I will not die immediately. I wish to live a little longer, even if it is just for a few seconds more. So you should leave."

The Gu replied, "Oh human, among the three, I have the smallest need. Human, if you give me your heart, it will be enough".

Ren Zu asked one final question, "Oh Gu, I will give you my heart, but what can you give me in return? In this situation, even with Strength and Wisdom Gu - it would not be enough!"

When compared to the mighty Strength Gu, or the captivating Wisdom Gu - this Gu looked frail, and was just a tiny ball of light. But, when Ren Zu gave his heart to this Gu, it suddenly gave out endless light. In this light, the Predicaments screamed in horror: "This is Hope Gu! Withdraw! We predicaments are most afraid of hope!"

The predicaments retreated suddenly. Ren Zu was amazed, and from that day onwards - whenever he faced a predicament, he would give his heart to hope.

* So, what's the big deal?

You might be saying - "DeadMeme, I expected a work of art - but you give me a children's story about 'hope'?"

Patience, my dear friend. This, was just chapter ONE. The beginning of the legends. And however pretentious I may sound, even chapter one has certain depth that might be obvious, but I shall still highlight what I've learnt from it.

When I realised I was alive, the first thing - as any rebellious teenager would do - I craved strength. Not just in physical strength in my fights at school, but also strength in the situation, to be truly out of reach. To be able to scorn and face no consequences, to muscle my way through any situation. No problem I had faced - was stronger than "strength".

This pattern I've begun to observe in people younger than me as well. They crave power and dominance. They wish to be the strongest there is. They truly believe that nothing can beat them as long as they are "strong".

Then, one shifts to "wisdom". I sought intelligence, the ability to reflect, the ability to strategize. No situation in the world was unsolvable when one is strong AND smart. This at the face level makes the most sense. One can see the world and their ability reflected in just these 2 facets - how strong they are, and how smart they are.

Most people stop here. Obviously there is a gradient in the strength and intelligence of people, but they wish for these 2 things - most of their lives. They wish to be strong enough to overcome the problems they face, or be smart - when strength doesn't cut it as a solution to the predicament they are in.

* And? This seems fine. Predicaments seem to be dealt with then?

Not really. As one of my personal favorite philosophers - Albert Camus says in "The Myth of Sisyphus" - "One day - The absurd is born of this confrontation between the human need [for meaning] and the unreasonable silence of the world. At this point of his journey the absurd man pronounces judgment. He says that the world is crazy. He takes the first decisive step of his life."

This moment - is what I personally believe "old age" in the context of Ren Zu means. It is not the frailty of body, but of the mind - where the tiredness of having to confront predicaments on a daily basis, however big, however small. This exact moment is when a person's strength leaves him, his wisdom leaves him - and he is resigned to accept his fate and give up. Finally - the predicaments have beaten him down. They win.

At this moment, the only savior of any man, the one that fills you with light - is Hope. No problem can stand the test of hope. No predicament is too big, if one gives their heart (not their brain, mind you), to Hope.

We don't wake up daily because we are strong enough to wake up and face anything. We don't wake up because we are smart enough to strategize against our problems. The truest force that drives us to wake up every day is Hope. Hope that things will get better, and this hope - truly scares away predicaments, and keeps them at bay.

* Just a few words more...

I believe, Hope is meaningful for a man's existence. With the light of hope, no predicament is too big, too scary or too vicious. Because the light of hope invigorates the heart of man. It shines through and keeps a man going, and relieves one from the sense of burden, frailty and tiredness.

So, with all this anon, what do you hope for? What is the hope that keeps you alive, and moves you to wake up everyday?
