#+TITLE: Chapter Two - Rules and Regulations.
#+DATE: <2026-01-02>
#+FILETAGS: :reverend_insanity:

* Chapter Two - Rules and Regulations.

Ren Zu was finally able to keep predicaments at bay, and still live with hope. But eventually, he grew old and without Strength and Wisdom Gu, he could no longer continue to hunt. Even his teeth fell off, making him unable to chew even the wild fruits and vegetables he foraged for.

Ren Zu felt death slowly approaching. At this time, Hope Gu in his heart said, "Human, you must not die. If you die, your heart will be lost and I will lose my only place of residence."

Ren Zu felt helpless, "Who wishes to die? But if the heavens and earth want me dead, I have no choice."

Hope Gu replied, "There's always hope in everything. As long as you can catch a Longevity Gu, you will be able to increase your lifespan!"

Ren Zu had heard of the existence of Longevity Gu, but he waved his hand helplessly. "When the Longevity Gu stays still, nobody can detect it and when it flies, it is faster than light. How can I possibly catch it? It's too hard..."

Hope Gu then told Ren Zu a secret, "Human, don't give up hope no matter what. Let me tell you, on the northwest corner of this continent, there is a huge mountain. On the mountain, there is a cave and in that cave, this are a pair of round and square Gu Worms. As long as you can subdue them, there is no Gu in this world you cannot catch, including the Longevity Gu!"

Ren Zu had no choice, he clung to his last remaining hope and braved all difficulties and finally found the mountain. He then risked his life and ventured through countless dangers to ascend the mountain. On the mountain top, near the cave entrance, he used his last remaining strength to slowly make his way in.

The inside of the cave was completely dark, so dark that one would not even be able to see their own hands. Ren Zu felt lost as he bumped into things, not knowing what they were. This caused him to get injured and wounded all over. At times, he felt like this cave had nothing but emptiness and he wondered how he would subdue the two gu worms.

When he was at a loss about what to do, two voices spoke to him from the darkness. "Human, you're here to catch us? Go back, for even if you had the Strength Gu, it would be impossible to make us obey you."

The other said, "Human, go back, we will not take your life. Even if you had the Wisdom Gu to help you, you may not be able to command us."

Ren Zu lay exhausted on the ground, panting. "Strength and Wisdom Gu have abandoned me, and I do not have much lifespan left so I'm at my wits end. But as long as there is Hope in my heart, I will not give up!"

Hearing Ren Zu's words, the two Gu went silent. After a while, one of them said "I understand human, you have already given your heart to hope Gu. You will not give up no matter what."

The other continued, "In that case, we shall give you a chance. As long as you can say our names - we will allow you to use us."

Ren Zu was stunned. To find their names among all the words in the world, it was akin to finding a needle in a haystack. Moreover, he did not even know how many words were in their names.

Ren Zu quickly asked the Hope Gu, but it didn't know either. Ren Zu had no choice but to randomly guess their names. He kept reciting many many names, and wasted a lot of time but the darkness did not respond to him.

Eventually, Ren Zu's breath got weaker as death's shadow crept up on him. It was like the scene of the evening's setting sun. The sun which was slowly descending, had already lowered halfway across the horizon, becoming a sunset.

The food he had brought had gradually reduced, his brain becoming slower and he barely had any energy left.

The voice in the darkness urged, "Human you are almost dead, so we will let you leave. Using your remaining time, you can climb out of the cave and take one final look at the world. But you have offended us, and as punishment, Hope Gu shall stay here as our companion."

Ren Zu clenched his heart and rejected the unknown Gu outright. "Even if I die, I will not give up hope!"

Hope Gu was very touched and answered Ren Zu's call enthusiastically, emitting a bright light. His heart bloomed with pure white light. But this light was too weak. It was barely able to cover Ren Zu's entire body, only pulsing at his chest.

Yet, Ren Zu could feel a renewed sense of energy gush into his body, from the Hope gu residing in his heart.

He continued to speak, shouting out names. He was already muddled, and kept wasting his breath - his precious lifespan that was withering away, as he kept screaming names he had already said.

Finally, when he was on his last day, he said the word "Regulation!"

A sigh came from the darkness as a voice spoke, "Human, I admire your effort and will. You have said my name, so from today onwards, I will obey your commands. But only with my brother can I aid you in capturing all the Gu in the world. Otherwise, with my ability alone, it is impossible. Thus, you should give up and might as well use this chance to take a final look at the world."

Ren Zu shook his head. Full of determination, he made use of every single breath and continued to shout out names, as he tried to guess the other Gu's name.

Time flew, as he neared his end, and soon he had only one hour left.

But at this time, he unknowingly said the word "Rule!"

Immediately, the darkness in the cave completely dissipated. The two Gu appeared in front of him, As Hope Gu said, one was cubic, called "Regulations". The other was spherical, called "Rules". Together they made up, "Rules and Regulations".

The two Gu said together, "No matter who it is, as long as they know our name - we will obey them. Human, since you know our names already, we will be at your service. But you must remember, it is important to not let others know of our names. The more people that know our names, the more people we have to obey. Now that you are the first to subdue us, tell us your request".

Ren Zu was overjoyed, he immmediately ordered them, "I command you both to capture me a Longevity Gu."

The Rules and Regulations Gu worked together and captured him an 80 year Longevity Gu.

Ren Zu was already nearly a hundred years old, but after consuming the Gu, the wrinkles on his face disappeared and his limbs became muscular again. A vibrant aura of youth oozed from him.

With a belly flop. He jumped to his feet, ecstatic about finally regaining the body of a twenty year old.

* So, what's the big deal Now?

DeadMeme, you claimed to see the "inner meaning" of the story of Hope, talking about how Hope is more important than Strength and Wisdom. But, C'mon - this is just a children's story about how some guy "filled with hope", was able to somehow regain his youth. By using "Longevity Gu". There is no Longevity Gu in our world buddy, we die when we die. Not even "Hope" or "Rules and Regulations" can save you from that.

My claim isn't going to be that someone is going to suddenly gain lifespan by naming a circle and a rectangle in a dark cave on a strange mountain. My claim is far more interesting - as this story is narrated in the context of the protagonist of the main book.

So, let me tell you what you might be missing. This story follows from Ren Zu gaining Hope, but Hope by itself does nothing, as age swallows you whole. As time passes, Hope enough might give you the energy to continue, but just like Ren Zu - you will find yourself lost, and bump into things you don't even understand.

So, what does one need - when Hope provides energy, but one still waddles in the dark? The answer, is knowledge of the 2 things that run the world, from the darkness. Rules, and Regulations. Understanding them, gives one the ability to "capture any gu", in the real world - I believe to be the equivalent to getting what one wants.

But, the path to grasping and understanding these "Rules and Regulations" is a dangerous one. One must trek through to the top of a remote mountain, and be lost in the darkness - while they keep trying to identify what these rules and regulations actually are. The same effort Ren Zu put into identifying the names of these 2 Gu, one must put into grasping the true Rules and Regulations of the world one operates in.

As one keeps trying, they will dissuade you from trying. They will tell you to give up, and just "enjoy the world". And as they wish for you to give up, they will take away the one energy source you have, pushing you forward to identifying these invisible binds that can capture anything - "Hope". Just as they told Ren Zu - You have offended us, but you may leave, and we WILL take your Hope from you.

This to me, hit the hardest. One struggles in the world, to identify the rules and regulations that exist, that they and the ones around them operate on. They struggle to identify them, and when one gets it wrong - one is told to give up and that offense has been caused. This to me is the same as figuring out how people operate, how organizations operate, how the world works. And in the process of figuring it out, we tend to lose Hope, and to "finally gaze upon the world one last time", while the Rules and Regulations claim another one's life.

You see this all around you - people going from excited rebellious teenagers, full of life - to sapped adults that tell you they have "accepted" what life has for them, and that they are "mature enough" to understand when to settle. That - is when their Hope was stolen from them by Rules and Regulations. That, is when they resigned themselves to their fate, devoid of any hope.

Machiavelli saw this. Robert Greene writes about this. The Rules exist whether you acknowledge them or not, shrouded in darkness, exerting their will over you. Most people believe that the world runs on fairness, justice and merit. They believe in the value of agreements, not truly understanding the Rules and Regulations operating in the darkness. The ones who understand, get called "lucky" or "blessed" and are envied for their apparent ability to not yield. They get called "deviants" and "disrespectful" at worst.


* So what must one do?

Keep trying, never losing Hope. Here's the thing about Rules and Regulations - once you finally understand (name) them, they're just a sphere and a cube. The complexity was never the Rules and Regulations themselves. It was in the darkness. And they'll "serve" anyone who knows their names and understands what they are. But they ask you not to share. The more people who understand them, the more masters they obey, the weaker they become.

This is why the people who truly understand how things work rarely explain it. It's not selfishness - sometimes the explanation genuinely doesn't help. You can't take a shortcut from the stumbling. The darkness is for you to dissipate, with the light of your Hope.

Ren Zu jumped to his feet. Full of youth, having captured a Longevity Gu. But, in the real world - there is no magic potion, just Hope and constantly trying and not willing to let them claim you. The weakness and frailty is never your body. It was the confusion that stemmed from being lost in the dark. Once that is lifted, the darkness dissipates. You see the shapes. You are no longer bound by them anymore.

But what happens when you start abusing your understanding of these Rules and Regulations?

That's for you to find out in Chapter Three - Attitude, Belief, and Suspicion.
